### ISSUE TITLE
new reply with tracking shows that message as unread

### ISSUE THREAD

**Issue by jcs** [kawf/kawf#6]
In fecca9c2aa the commit message says "use current thread timestamp, rather than NOW(), so that newly posted messages show as unread".

This behavior seems counter-intuitive.  When I post a new reply in an existing thread and start tracking it for the first time, my reply always bumps the thread to the top as an updated tracked thread, requiring that 'up' is clicked just to mark my own reply as read.

Do you remember why this was requested?  The bugs on the sourceforge repo are only two digits, so I'm not sure which bug tracker the bug numbers in the commit message are referring to.

**Comment by nyetwurk** [comment]
I did that because i prefer it that way... I like being able to immediately see my post in context and have the option to click on it and see if it needs revision in the context in which it was just posted.

More importantly, if someone posts while you are composing your own message, those posts never show as unread.

**Comment by jcs** [comment]
> More importantly, if someone posts while you are composing your own message, those posts never show as unread.

I don't think that even works though, because it's selecting `f_threads*.tstamp` at the time you post, which could have been bumped up by a bunch of posts prior to yours, but after the timestamp you saw when the page was rendered, so you'd miss all those posts.

To fix both problems (though I guess the first one isn't a problem if you want that behavior), the message post form could include the thread's max `mid` at time of generation and in `postmessage()` just `select max(mid) from $mtable where tid = $msg['tid']` and if it's higher than the passed-through `mid`, you know you have unread messages to view, and you should take the timestamp of that passed-through message id's `date` column as the `tstamp` for the `f_tracking` row.  That will guarantee you see all new posts made between when you saw the thread and when you posted in your tracked thread.

If the `mid` is equal, your post is the new highest in the thread, you know there were no new posts between when you saw the thread and you posted, and your `tstamp` for `f_tracking` can now be the `tstamp` on your just-added `f_messages*` row.

**Comment by nyetwurk** [comment]
Correct, it definitely doesn't work 100%, and the solution you describe (or something similar to it, comparing max mid with your mid) was in a branch that I threw out because it had all sorts of other complicated junk in it. If you can make a good solution and preserve my (admittedly kind of silly) preference, I'll definitely take it.

**Comment by jcs** [comment]
I got most of the way there but died trying to figure out all the local time/unix timestamp mess.

⚰

**Comment by nyetwurk** [comment]
I did that because i prefer it that way heh.

**Comment by nyetwurk** [comment]
Also if someone posts while you are composing your message, those posts never show as unread.
